== ptranslator - rhq-metrics restServlet proxy

This is a proxy server taking in metrics data in one format and emitting
them as rest-requests into rhq-metrics backend.

You can configure ports to use in a `ptrans.properties` file. Default
for TCP is port 5140.

=== Formats

==== Syslog

This module contains a simple proxy server that also listens on UDP port 5140
for syslog messages. If a message is of the format

  type=metric thread.count=7 thread.active=5 heap.permgen.size=20000000

Then it is taken and the individual key-value-pairs are broken apart and
sent as individual metrics to a rhq-metrics rest server. The timestamp
is the current time on the proxy when the udp packet was received.

==== Graphite

The converter also accepts Graphite plaintext format

    path value timestamp_in_s

or with multiple entries per message

    path1 value1 timestamp_in_s1
    path2 value2 timestamp_in_s2

==== StatsD

The converter accepts statsD packets sent via UDP (to the UDP port).
Format is

  key:value|type


Where only key and value are accepted and the type is ignored (for now).



=== running

  $ java  -cp ~/.m2/repository/io/netty/netty-all/4.0.19.Final/netty-all-4.0.19.Final.jar:target/syslog-rest-0.1.0-SNAPSHOT.jar\
        :~/.m2/repository/org/slf4j/slf4j-log4j12/1.7.7/slf4j-log4j12-1.7.7.jar:/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar\
        :~/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar org.rhq.metrics.clients.ptrans.Main

Before you start the proxy, make sure the rest-server is running.

=== Configuring syslog

You need to configure syslog to forward you the messages.
For this you need to edit `/etc/syslog.conf` and add a line like this:

  *.info          @127.0.0.1:5140

(the facility and severity may vary depending on how your application is logging the metrics)

=== Manually testing

On a *nix command line you can run

  $ logger -p local3.info "type=metric thread.count=7 thread.active=5 heap.permgen.size=20000000"

to add entries to syslog for testing purposes.

=== Room for improvement:

* add information about the remote to the key so make the key unique
* reconnect to the rest server if it goes down
* add a syslog file tailer
* allow to start even if the rest server is not available
* allow for more syslog formats
* support reliable syslog protocol