= hawkular-metrics
:source-language: java

ifdef::env-github[]
[link=https://travis-ci.org/hawkular/hawkular-metrics]
image::https://travis-ci.org/hawkular/hawkular-metrics.svg?branch=master[Build Status,70,18]
[link=https://scan.coverity.com/projects/4581"]
image::https://scan.coverity.com/projects/4581/badge.svg[Coverity Scan Build Status (coverity_scan branch)]
endif::[]

= Project to implement a MaaS and ChaaS

* MaaS: Metrics as a Service
* ChaaS: Charts as a Service

== Quickstart

To get a first impression you can also run the quickstart via

  ./start.sh

in the root directory. This will build and start Hawkular-metrics with the in-memory backend. After starting you can
 navigate to http://localhost:8080/[http://localhost:8080/] to a UI Dashboard that displays a list of metrics and the ability to graph multiple charts.
 [NOTE: it will initially be empty if you don't have anything in your database.]

Or, if you want to just play around with creating your own metric data and visually see the results in graphs then the Explorer web application is what you want.
  Available at: http://localhost:8080/explorer/[http://localhost:8080/explorer]

https://vimeo.com/101576357[RHQ Metrics Explorer UI Video]   _Length - 8:33_

By modifying the start parameter in the script you can also use the (already running) Cassandra backend - see below.


== Build Instructions

This project has a dependency on Cassandra 2.1.1 or later. A running Cassandra cluster, which can be a single node, is required
for unit and integration tests.

TIP: If you only want to build the sources without a running C* cluster, you can run `mvn install -DskipTests`.
Building without C* also means that no schema updates are applied.


== Setting up Cassandra

1. Install https://github.com/pcmanus/ccm[ccm].
  a. Review its build/install instructions for python package dependencies that need to be installed, namely six and pyYaml.
2. `ccm create -v 2.1.2 hawkular`
3. `ccm populate -n 1`
4. `ccm start`
5. `mvn install`

These steps build and install a single node cluster of Cassandra 2.1.2. Note that while it is recommended to use ccm, it
is not necessary. You just need to make sure you have a running 2.1.x cluster.

=== Installing ccm

ccm is a python module that has a dependencies on several other python modules.

= Import data from Ganglia

If you have Ganglia `gmond` running, you can import its data by running the pTrans client:

----
cd clients/ptranslator
sh start.sh
----

For this to work, the packets from Ganglia need to have a large enough TTL to be seen on the host where you run pTrans.

# Forums, hacking, irc

If you are a user of Hawkular Metrics please ask your question in the https://developer.jboss.org/discussion/create.jspa?containerType=14&containerID=2351[Hawkular user forum],
if you are willing to contribute or participate in design discussion, please use the
https://lists.jboss.org/mailman/listinfo/hawkular-dev[Hawkular developer mailing list]

We love contributions and pull-requests :-)

To meet the guys, join us on irc://irc.freenode.net/#hawkular[Freenode IRC] in channel #hawkular.
If you can not use the irc protocol, you can also use a web to irc gateway like
http://webchat.freenode.net/?channels=hawkular[Web chat on Freenode].

Hawkular-metrics is http://twitter.com/#!/hawkular_org/[@hawkular_org] on Twitter.
