= Hawkular Metrics, a storage engine for metric data
:source-language: java

ifdef::env-github[]
[link=https://travis-ci.org/hawkular/hawkular-metrics]
image::https://travis-ci.org/hawkular/hawkular-metrics.svg?branch=master[Build Status,70,18]
[link=https://scan.coverity.com/projects/4581"]
image::https://scan.coverity.com/projects/4581/badge.svg[Coverity Scan Build Status (coverity_scan branch)]
endif::[]

== About

Hawkular Metrics is the metric data store for the http://www.hawkular.org/[Hawkular] project.
It can also be used independently.

It relies on https://cassandra.apache.org/[Apache Cassandra] as a backend and is comprised of:

- a core library
- a REST/HTTP interface

IMPORTANT: Cassandra 2.1.5 or later is required. It is recommended to use the latest 2.1.x release if possible.

=== The core library

A Java library, built with https://github.com/ReactiveX/RxJava[RxJava] on top of the Cassandra Java driver.

This is for advanced users only, if you want to embed the core functionnality in another product.

=== REST/HTTP interface

Most users will work with the
https://github.com/hawkular/hawkular-metrics/tree/master/api/metrics-api-jaxrs[web application].
It exposes a REST/HTTP interface based on the core library. It is implemented with the JAX-RS 2 asynchronous API and
runs on a http://www.wildfly.org/[Wildfly] server. The data format is JSON.

== Goals

=== Simple, easy to use REST interface

The http://www.hawkular.org/docs/rest/rest-metrics.html[REST API] should be easy to use. Users should be able to send
data with the simplest tools: shell scripts and `curl`.

=== Speed

Design choices are driven with throughput in mind: we want Metrics to be able to ingest as many data points per minute
as possible.

== Getting started with a release build

http://wildfly.org/downloads/[Download a Wildfly 9] archive and expand it somewhere on your disk.

Check out the https://github.com/hawkular/hawkular-metrics/releases[Metrics releases] page and download the latest
version of the web application archive: `hawkular-metrics-api-jaxrs-X.Y.Z.war`

Copy this file to the `standalone/deployments` directory of the Wildfly server.

Start the server with `bin/standalone.sh`.

By default, Metrics will try to connect to a Cassandra on localhost. If you want to start a Cassandra server
embedded into Wildfly for testing, add the `hawkular-metrics-embedded-cassandra-ear-X.Y.Z.ear` archive to the
`standalone/deployments` directory.

== Build Instructions

IMPORTANT: A running Cassandra cluster, which can be a single node, is required for unit and integration tests.

[source,bash]
----
git clone git@github.com:hawkular/hawkular-metrics.git
cd hawkular-metrics
mvn install
----

TIP: If you only want to build the sources without a running C* cluster, you can run `mvn install -DskipTests`.

== Setting up Cassandra for development or testing

For development or testing, the easiest way to setup Cassandra is to use the
https://github.com/pcmanus/ccm[Cassandra Cluster Manager, CCM].

[source,bash]
----
ccm create -v 2.1.5 hawkular
ccm populate -n 1
ccm start
----

These steps build and start a single node cluster of Cassandra 2.1.5. Note that while it is recommended to use ccm, it
is not necessary. You just need to make sure you have a running 2.1.x cluster.

== Working with monitoring tools

You can send data collected with your usual monitoring tools to Hawkular Metrics:

- collectd
- ganglia
- jmxtrans
- statsd

In order to do so, you must start our network protocol adapter,
https://github.com/hawkular/hawkular-metrics/tree/master/clients/ptranslator[ptrans].

== Forums, hacking, irc

If you are a user of Hawkular Metrics please ask your question in the
https://developer.jboss.org/discussion/create.jspa?containerType=14&containerID=2351[Hawkular user forum],
if you are willing to contribute or participate in design discussion, please use the
https://lists.jboss.org/mailman/listinfo/hawkular-dev[Hawkular developer mailing list]

We love contributions and pull-requests :-)

To meet the guys, join us on irc://irc.freenode.net/#hawkular[Freenode IRC] in channel #hawkular.
If you can not use the irc protocol, you can also use a web to irc gateway like
http://webchat.freenode.net/?channels=hawkular[Web chat on Freenode].

Hawkular-metrics is http://twitter.com/#!/hawkular_org/[@hawkular_org] on Twitter.
