
== Overview

=== Media Type

The API uses *JSON* to communicate with clients.

You _should_ add the following accept header to your requests:

----
Accept: application/json
----

When you send JSON data with a `POST` or `PUT` request, you _must_ add the following content type header:

----
Content-Type: application/json
----

=== JSON format

The server does not include null or empty entity properties in JSON representations.

[source,javascript]
----
// Metric with data
{
  "id": "paris01.web001.example.com.cpu.usage",
  "data": [
    {"timestamp": 10101010101, "value": 25.73}
  ]
}

// Metric without data
{
  "id": "paris01.web001.example.com.cpu.usage"
}
----

=== Tenant Header

Hawkular Metrics is a multi-tenant time-series data store. Your requests to tenant-dependent resources must include
a tenant header:

----
Hawkular-Tenant: my-tenant
----

=== Timestamps

The API understands all timestamps as milliseconds since January 1, 1970, 00:00:00 UTC.

=== Response codes

Resources in the API follow response codes conventions, listed below.

.Response codes conventions
[cols="30,70a", options="header"]
|===
|Response code |Meaning

|200 Ok
|The operation completed successfully.

|201 Created
|A `POST` or `PUT` operation to create an entity completed successfully.
The reponse should contain a `Location` header.

|204 No Content
|The operation completed successfully but result entity is null (`object`) or empty (`array`).
Empty arrays are not sent in the response body.

|400 Bad Request
|The operation could not be processed. It could be due to:

* Missing or malformed request entity
* Missing header/query parameter
* Malformed path/header/query parameter
* Invalid parameters (breaking business rules)

|404 Not Found
|Resource denoted by the URI does not exist.

|405 Method Not Allowed
|Resource denoted by the URI does not support the operation type.

|406 Not Acceptable
|Cannot reply in a format accepted by the client (specified in `Accept` request header).

|409 Conflict
|A `POST` or `PUT` operation could not be performed because it conflicts with an existing entity.

|415 Unsupported Media Type
|Invalid request entity format. For example, `text/plain` whereas `application/json` is expected.

|500 Internal Server Error
|Resource operation failed unexpectedly.

|503 Service Unavailable
|The server failed to initialize or the storage backend is not ready yet.
|===

=== Errors

TBW: about error format and usual errors

=== Time ranges

TBW: about start and end params, and default values, and order constraint

=== Bucket parameters

TBW: about bucket parameters (should use just one of the two parameters, ... etc)

=== Custom string formats

Some path or query parameters in the Metrics REST API use custom string formats.

==== Tags list

The parameter represents a list of tags, comma separated. A tag has the form `name:value`.
Name and values cannot contain commas or colons.

Throughout this document, this string format is identified as `tag-list`.

.Tags List format example
----
/metrics?tags=host:web001.example.com,dc:paris01,type:system
----

==== Duration

The parameter represents an amount of time. Duration is formed of a length and a unit.

Length is a long integer (`int64`).

Allowed units are the following:

* `ms` for milliseconds
* `s` for seconds
* `mn` for minutes
* `h` for hours
* `d` for days

Throughout this document, this string format is identified as `duration`.

.Duration format example
----
/gauges/paris01.web001.example.com.cpu.usage/data?bucketDuration=1h
----
