
== Overview

=== Media Type

The API uses *JSON* to communicate with clients.

You _should_ add the following accept header to your requests:

----
Accept: application/json
----

When you send JSON data with a `POST` or `PUT` request, you _must_ add the following content type header:

----
Content-Type: application/json
----

=== JSON format

The server does not include null or empty entity properties in JSON representations.

[source,javascript]
----
// Metric with data
{
  "id": "paris01.web001.example.com.cpu.usage",
  "data": [
    {"timestamp": 10101010101, "value": 25.73}
  ]
}

// Metric without data
{
  "id": "paris01.web001.example.com.cpu.usage"
}
----

=== Tenant Header

Hawkular Metrics is a multi-tenant time-series data store. Your requests to tenant-dependent resources must include
a tenant header:

----
Hawkular-Tenant: my-tenant
----

=== Timestamps

The API understands all timestamps as milliseconds since January 1, 1970, 00:00:00 UTC.

=== Response codes

Resources in the API follow response codes conventions, listed below.

.Response codes conventions
[cols="30,70a", options="header"]
|===
|Response code |Meaning

|200 Ok
|The operation completed successfully.

|201 Created
|A `POST` or `PUT` operation to create an entity completed successfully.
The reponse should contain a `Location` header.

|204 No Content
|The operation completed successfully but result entity is null (`object`) or empty (`array`).
Empty arrays are not sent in the response body.

|400 Bad Request
|The operation could not be processed. It could be due to:

* Missing or malformed request entity
* Missing header/query parameter
* Malformed path/header/query parameter
* Invalid parameters (breaking business rules)

|404 Not Found
|Resource denoted by the URI does not exist.

|405 Method Not Allowed
|Resource denoted by the URI does not support the operation type.

|406 Not Acceptable
|Cannot reply in a format accepted by the client (specified in `Accept` request header).

|409 Conflict
|A `POST` or `PUT` operation could not be performed because it conflicts with an existing entity.

|415 Unsupported Media Type
|Invalid request entity format. For example, `text/plain` whereas `application/json` is expected.

|500 Internal Server Error
|Resource operation failed unexpectedly.

|503 Service Unavailable
|The server failed to initialize or the storage backend is not ready yet.
|===

=== Error responses

Error responses may include an <<ApiError>> entity in the body.

.Sample error entity
[source,javascript]
----
{"errorMsg":"Tenant is not specified. Use 'Hawkular-Tenant' header."}
----

=== Time ranges

Many resource operations need a time range restriction to be processed.

Such operations accept two <<_timestamps,timestamp>> query parameters:

* `start`: the beginning of the time range, inclusive
* `end`: the end of the time range, exclusive

Either or both of them can be omitted. `start` defaults to _now_ minus 8 eight hours. `end` defaults to _now_.

`end` must be strictly bigger than `start` otherwise the resource operation returns a `400 Bad Request` response.

.Sample operations with time range query parameters
[source,bash]
----
# Implicit time range
/hawkular/metrics/gauges/paris01.web001.example.com.cpu.usage/data

# Implicit time range
/hawkular/metrics/gauges/paris01.web001.example.com.cpu.usage/data?start=10101010

# Explicit time range
/hawkular/metrics/gauges/paris01.web001.example.com.cpu.usage/data?start=10101010&end=20202020

# Implicit time range
/hawkular/metrics/gauges/paris01.web001.example.com.cpu.usage/data?end=20202020
----

=== Limit and Order

The API offers the ability to limit the number of data points returned as well specify the order of the results.
Limit and order only work with raw data; if used in conjunction with bucketed results, it will return an error.

Usage and default value details:

* ascending order parameter value is `asc`
* descending order parameter value is `desc`
* parameter value matching is case-insensitive
* default order is descending
* no limit imposed if parameter not specified
* limit of 0 or negative is equivalent to no limit
* if the user specifies limit, then the order is important because it returns data points up to limit in the specified order
* start time and end time influence the default order if actual limit is specified
 ** if only start time is specified then order is ascending
 ** if only end time is specified then order is descending
 ** if both are specified then order is descending
 ** if none are specified then order is descending
 ** order defaults are overridden if order specified
* default order is descending if limit is not specified regardless of specified time range

NOTE: please refer to `Time Ranges` section for defaults when omitting end, start, or both.

Sample operations with time range query parameters
[source,bash]
----
# Implicit time range, not limit, and descending order
/hawkular/metrics/gauges/paris01.web001.example.com.cpu.usage/data

# Explicit limit of 10, implicit time range, implicit descending order
/hawkular/metrics/gauges/paris01.web001.example.com.cpu.usage/data?limit=10

# Explicit limit of 10, implicit time range, explicit ascending order
/hawkular/metrics/gauges/paris01.web001.example.com.cpu.usage/data?limit=10&order=ASC

# Explicit limit of 10, explicit time range, implicit descending order
/hawkular/metrics/gauges/paris01.web001.example.com.cpu.usage/data?start=10101010&end=20202020&limit=10

# Explicit limit of 10, explicit start, implicit end, implicit ascending order
/hawkular/metrics/gauges/paris01.web001.example.com.cpu.usage/data?start=20202020&limit=10

# Explicit limit of 10, explicit start, implicit end, explicit descending order
/hawkular/metrics/gauges/paris01.web001.example.com.cpu.usage/data?start=20202020&limit=10&order=DESC
----

=== Bucket parameters

The API offers the ability to retrieve statistics on gauges, counter and availability metrics.
To compute these statistics, Hawkular Metrics slices a given <<_time_ranges,time range>> into _buckets_.

The size of _buckets_ is configurable. This allows to send a query to get, for example,
monthly statistics over a year of data, or hourly statistics over a week of data.

Bucket size is configured with either the `buckets` or the `bucketDuration` query parameter, exclusively:

* `buckets` indicates the desired number of buckets over the specified timerange
* `bucketDuration` forces bucket size to the specified amount of time

`bucketDuration` is a <<_duration, duration>>-formatted string.

If both parameters are specified, the resource operation returns a `400 Bad Request` response.


.Sample operations with bucket query parameters
[source,bash]
----
# Desired number of buckets
/hawkular/metrics/gauges/paris01.web001.example.com.cpu.usage/data?start=10101010&end=20202020&buckets=10

# Desired bucket size
/hawkular/metrics/gauges/paris01.web001.example.com.cpu.usage/data?start=10101010&end=20202020&bucketDuration=1mn
----

=== Custom string formats

Some path or query parameters in the Metrics REST API use custom string formats.

==== Tags list

The parameter represents a list of tags, comma separated. A tag has the form `name:value`.
Names and values cannot contain commas or colons.

Throughout this document, this string format is identified as `tag-list`.

.Tags List format example
----
/hawkular/metrics/metrics?tags=host:web001.example.com,dc:paris01,type:system
----

==== Duration

The parameter represents an amount of time. Duration is formed of a length and a unit.

Length is a long integer (`int64`).

Allowed units are the following:

* `ms` for milliseconds
* `s` for seconds
* `mn` for minutes
* `h` for hours
* `d` for days

Throughout this document, this string format is identified as `duration`.

.Duration format example
----
/hawkular/metrics/gauges/paris01.web001.example.com.cpu.usage/data?bucketDuration=1h
----
