= Hawkular Metric Containers
:type: article

Docker/Kubernetes modules

== Building the Docker Images

To build the docker images, you will need to have access to a machine running docker which has been configured to have its remote API exposed.

You will need to expose this host by using the environment variable `DOCKER_HOST` or by specifing the runtime property `-Ddocker.host`

You will also need to enable the `docker-build` Maven profile.

Example, assuming your docker host is running on your local machine, using the `tcp` protocol and listening on port `2375`:

[source,bash]
----
export DOCKER_HOST=tcp://127.0.0.1:2375
mvn clean install -Pdocker-build
----

or:

[source,bash]
----
mvn clean install -Pdocker-build -Ddocker.host=tcp://127.0.0.1:2375
----

== Running the Container Tests

The container tests are meant to be run on OpenShift v3 1.0.4

=== Download OpenShift and extract it

[source,bash]
----
wget https://github.com/openshift/origin/releases/download/v1.0.4/openshift-origin-v1.0.4-757efd9-linux-amd64.tar.gz[https://github.com/openshift/origin/releases/download/v1.0.4/openshift-origin-v1.0.4-757efd9-linux-amd64.tar.gz]
tar zxvf openshift-origin-v1.0.4-757efd9-linux-amd64.tar.gz
----

=== Expose the OpenShift binaries to $PATH

[source,bash]
----
export PATH=`pwd`:$PATH
----

=== Set the address you want openshift to be exposed at

WARNING: you cannot use `127.0.0.1` or `localhost` here as it needs to be an address which is resolvable from within docker containers

[source,bash]
----
export BINDING_ADDRESS=<INSERT-YOUR-BINDING-ADDRESS-HERE>
----

=== Create the configuration files you wish to use

[source,bash]
----
./openshift start --write-config=openshift.local.config --hostname=$BINDING_ADDRESS --public-master=$BINDING_ADDRESS
----

=== Temporary fix for heapster

For 1.0.4 heapster will not function properly due to it requring an non-secured `/stats` endpoint

You will need to configure OpenShift to expose the RO endpoint as being unsecured

Edit the `openshift.local.config/node-$BINDING_ADDRESS/node-config.yaml` to add the following at the end:

[source,bash]
----
cat >> openshift.local.config/node-$BINDING_ADDRESS/node-config.yaml << DONE
kubeletArguments:
 read-only-port:
 - "10266"
DONE
----

=== Starting OpenShift

IMPORTANT: You must start Openshift as `root`.

[source,bash]
----
openshift start --master-config=openshift.local.config/master/master-config.yaml --node-config=openshift.local.config/node-$BINDING_ADDRESS/node-config.yaml
----

NOTE: make sure that the logs say that the DNS server has been started properly

If you see something in the logs like `Could not start DNS: listen tcp 0.0.0.0:53: bind: address already in use` you will need to stop OpenShift and resolve the issue before continuing.
You should see something like this instead: `OpenShift DNS listening at 0.0.0.0:53`

=== Checking that OpenShift is up and running

[source,bash]
----
xdg-open https://$BINDING_ADDRESS:8443
----

NOTE: you may need to explicitly enter the https here, otherwise you might get nonsense bytes returned back

NOTE: OpenShift is using self signed certificates, so it there will be a warning in your browser about this.

By default, OpenShift will allow for any username and any password to login. Please see the OpenShift documentation on how to specify a different login mechanism.

By default, the user who logs in will not have any permissions. To give your `admin` user cluster admin priviledges, you can use the following command:

[source,bash]
----
oadm --config=`pwd`/openshift.local.config/master/admin.kubeconfig policy add-cluster-role-to-user cluster-admin admin
----

=== Firewall setup

Make sure your firewall settings let Docker containers reach your host. Also, the Openshift DNS service should be
accessible.

If you're on Fedora, change your firewall, runtime configuration
[source,bash]
----
firewall-cmd --zone=trusted --change-interface=docker0
----

Also, enable the DNS service in the `FedoraWorkstation` zone.

=== Deploying Hawkular Metrics with Cassandra and Heapster in OpenShift

A few steps will need to be followed to deploy Hawkular Metrics on top of OpenShift.


==== Creating and Deploying the Hawkular secret
You will first need to create the secret which will contain the SSL certificates used between the Hawkular Metrics
and Cassandra containers to enable SSL and certificate based authentication. This can be easily done by running the
'create-secret.sh' in the containers/scripts/secrets directory.

[source, bash]
----
./scripts/secrets/create-secret.sh
----

This script will prompt to enter some information required to create the certificates. Once the script is run, you will now have
a 'hawkular-secrets.json' file in that directory.

To add this secret to hawkular metrics, run the following command:
[source, bash]
----
oc create -f hawkular-secrets.json
----

==== Giving the Hawkular user Cluster Reader permissions
Heapster requires having read access to the cluster in order to be able gather metrics from the cluster. To give
the 'hawkular' user this permission you will need to run the following command:

[source, bash]
----
oadm policy add-cluster-role-to-user cluster-admin system:serviceaccount:default:hawkular
----

Note: if you are running the containers on a project other than 'default' you will need to replace
'default' in the previous command with the name of the project you are deploying into.

==== Deploying the Hawkular Metrics Kubernetes Application
Deploying the Hawkular Metrics Kubernetes application will deploy and configure the Hawkular Metrics container,
Cassandra container and Heapster container to OpenShift. No other steps are required and all the data gathered
from Heapster will be written into Hawkular Metrics automatically.

[source, bash]
----
oc create -f ./kubernetes/target/generated-app/hawkular-metrics-kubernetes-app/kubernetes.json
----

=== Running the Tests

To run the tests, you will need to specify the following environment variables:

[source,bash]
----
export OPENSHIFT_HOME=<DIRECTORY WERE YOU INSTALLED OPENSHIFT>
export KUBERNETES_TRUST_CERT=true
export KUBERNETES_MASTER=https://$BINDING_ADDRESS:8443
export KUBERNETES_CLIENT_CERTIFICATE_FILE=$OPENSHIFT_HOME/openshift.local.config/master/admin.crt
export KUBERNETES_CLIENT_KEY_FILE=$OPENSHIFT_HOME/openshift.local.config/master/admin.key
mvn clean install -Pcontainer-tests
----
