= Running

== Method 1 (easy)
`mvm clean install`

`mvn wildfly:run`

== Method 2
run `mvn install` to create the servlet and then drop it into a WildFly 8
instance into `standalone/deployments/` and start the server with `bin/standalone.sh`


= JAX-RS Endpoints

== Tenants

=== Create Tenant

*Request URI*

POST /hawkular-metrics/tenants

*Request Body*

[source,json]
----
{
  "id": "com.acme.eng",
  "retentions": {
    "numeric": 100,
    "availability": 80
  }
}
----

*Example Request*

----
curl -X POST http://localhost:8080/hawkular-metrics/tenants -d@request.json -HContent-Type:application/json
----


*Description*

Creates a new tenant. Only the `id` field is required. An error is returned if
a tenant with `id` already exists. All client requests include the tenant id.
For almost all operations, it is included in the request URI. For other
operations, like this one, it is specified in the request body.


`retentions` is like a template that specifies data retentions for metrics. The
values are integers and are interpreted as hours. For this example request body,
all numeric metric data will have a data retention of 100 hours by default.
Availability metric data will have a data retention of 80 hours by defatult.

NOTE: Clients are not required to create explicitly create a tenant before
starting to store metric data. It is recommended to do so
however to ensure that there are no tenant id naming collisions and to provide
default data retention settings.

=== Find Tenants

*Request URI*

GET /hawkular-metrics/tenants

*Example Request*

----
curl http://localhost:8080/hawkular-metrics/tenants
----


*Response Body*

[source,json]
----
[
  {
    "id": "com.acme.eng",
    "retentions": {
      "numeric": 100,
      "availability": 80
    }
  },
  {
    "id": "com.acme.eng.test"
  }
]
----

*Description*

Returns a list of tenants. Notice that the second object does not include a
`retentions` property, which is optional.

== Metrics

=== Create Numeric Metric

*Request URI*

POST /hawkular-metrics/{tenantId}/metrics/numeric

*Request Body*

[source,json]
----
{
  "name": "com.acme.eng.appsrv1.request_size",
  "metadata": {
    "units": "bytes",
    "env": "test"
  },
  "dataRetention": 96
}
----

*Example Request*

----
curl http://localhost:8080/hawkular-metrics/{tenantId}/metrics/numeric -d@request.json -HContent-Type:application/json
----

*Description*

Creates a numeric metric. Only the `name` property is required. An error is
returned if a metric with `name` already exists. `metadata` is map of arbitary
key/value pairs that applies to the time series as a whole. The `dataRetention`
property specifies the data retention in hours and overrides the data retention
specified at the tenant level.

NOTE: Clients are not required to explicitly create a metric before storing
data. Doing so however allows clients to prevent naming collisions and to specify
meta data and data retention.

=== Create Availability Metric

*Request URI*

POST /hawkular-metrics/{tenantId}/metrics/availability

*Example Request*

----
curl http://localhost:8080/hawkular-metrics/{tenantId}/metrics/availability -d@request.json -HContent-Type:application/json
----

*Description*

The request body is the same as creating a numeric metric.


=== Find Metrics

*Request URI*

GET /hawkular-metrics/{tenantId}/metrics

*Query Parameters*

|===
|Name |Description

|type
|Accepted values are `num` and `avail`

|===

*Example Request*

----
curl http://localhost:8080/hawkular-metrics/{tenantId}/metrics?type=num
----

*Response Body*

[source,json]
----
[
  {
    "name": "com.acme.eng.appsrv1.request_size",
    "metadata": {
      "units": "bytes",
      "env": "test"
    },
    "dataRetention": 96
  },
  {
    "name": "com.acme.eng.appsvr1.request_count"
  }
]
----

*Description*

Returns a list of metrics. The results do *not* include metric data points. The
`metadata` and `dataRetention` properties are optional.

=== Update Metric Meta Data

*Request URI*

PUT /hawkular-metrics/{tenantId}/numeric/{id}/meta

*Request Body*

[source,json]
----
{
  "attr1": "value 1",
  "attr2": "value 2"
}
----

*Example Request*

----
curl -X PUT http://localhost:8080/hawkular-metrics/{tenantId}/metrics/numeric -d@request.json -HContent-Type:application/json
----

*Description*

The `attr1` and `attr2` keys are _upserted_. That is, the keys are created are
either created or overwritten.

== Metric Data

=== Add Numeric Data for a Single Metric

*Request URI*

POST /hawkular-metrics/{tenantId}/metrics/numeric/{id}/data

*Request Body*

[source,json]
----
[
  {"timestamp": 1416857688195, "value": 2.1},
  {"timestamp": 1436857688195, "value": 2.2},
  {"timestamp": 1456857688195, "value": 2.3}
]
----

*Example Request*

----
curl -X POST http://localhost:8080/hawkular-metrics/{tenantId}/metrics/numeric/{id}/data -d@request.json -HContent-Type:application/json
----

*Description*

Inserts data for a single numeric metric. The request body is an array of data
points where each one consists of `timestamp` and `value` properties.

=== Add Availability Data for a Single Metric

*Request URI*

POST /hawkular-metrics/{tenantId}/metrics/availability/{id}/data

*Request Body*

[source,json]
----
[
  {"timestamp": 1416857688195, "value": "down"},
  {"timestamp": 1416857688195, "value": "up"}
]
----

*Example Request*

----
curl -X POST http://localhost:8080/hawkular-metrics/{tenantId}/metrics/availability/{id}/data -d@request.json -HContent-Type:application/json
----

*Description*

Inserts data for a single availablity metric. Accepted values are the strings
`up` and `down`.

=== Insert Data for Multiple Numeric Metrics

*Request URI*

POST /hawkular-metrics/{tenantId}/metrics/numeric/data

*Request Body*

[source,json]
----
[
  {
    "name": "appsrv1.request_time",
    "data": [
      {"timestamp": 1416857688195, "value": 2.1},
      {"timestamp": 1436857688195, "value": 2.2}
    ]
  },
  {
    "name": "appsrv1.response_time",
    "data": [
      {"timestamp": 1416857688195, "value": 2.1},
      {"timestamp": 1436857688195, "value": 2.2}
    ]
  }
]
----

*Example Request*

----
curl -X POST http://localhost:8080/hawkular-metrics/{tenantId}/metrics/numeric/data -d@request.json -HContent-Type:application/json
----

*Description*

Insert data for multiple numeric metrics.

=== Insert Data for Multiple Availability Metrics

*Request URI*

POST /hawkular-metrics/{tenantId}/metrics/availability/data

*Request Body*

[source,json]
----
[
  {
    "name": "appsrv1",
    "data": [
      {"timestamp": 1416857688195, "value": "up"},
      {"timestamp": 1436857688195, "value": "up"}
    ]
  },
  {
    "name": "appsrv2",
    "data": [
      {"timestamp": 1416857688195, "value": "down"},
      {"timestamp": 1436857688195, "value": "up"}
    ]
  }
]
----

*Example Request*

----
curl -X POST http://localhost:8080/hawkular-metrics/{tenantId}/metrics/availability/data -d@request.json -HContent-Type:application/json
----

*Description*

Insert data for multiple availability metrics.

=== Retrieve Numeric data

*Request URI*

GET /hawkular-metrics/{tenantId}/metrics/numeric/{id}/data

*Request Parameters*

|===
|Name |Description

|start
|Defaults to now - 8hrs

|end
|Defaults to now

|buckets
|The number of buckets or intervals in which to divide the time range. A value of
60 for example will return 60 equally spaced buckets for the time period between
start and end times, having max/min/avg calculated for each bucket.

|===

*Example Request*

----
curl http://localhost:8080/hawkular-metrics/{tenantId}/metrics/numeric/{id}/data?start=1416857688195&end=1416857688195 -d@request.json -HContent-Type:application/json
----

*Response Body*

[source,json]
----
{
  "tenantId": "com.acme.eng",
  "name": "appsrv1.request_time",
  "metadata": {
    "env": "test",
    "units": "milliseconds"
  },
  "data": [
    {
      "timestamp": 1420392311670,
      "max": 75,
      "min": 25,
      "avg": 50
    },
    {
      "timestamp": 1420392311670,
      "max": 75,
      "min": 25,
      "avg": 50
    }
  ]
}
----
